##### NumPy arrays : A Multidimentional Array Object

In [1]:
import numpy as np

In [5]:
data = np.random.randn(2,3)

In [6]:
data

array([[-1.12618697,  0.35709996,  0.06849172],
       [ 0.72309381,  1.42242869,  1.66565052]])

In [7]:
data * 10

array([[-11.2618697 ,   3.57099961,   0.68491723],
       [  7.23093809,  14.22428685,  16.65650519]])

In [8]:
data + data

array([[-2.25237394,  0.71419992,  0.13698345],
       [ 1.44618762,  2.84485737,  3.33130104]])

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

# Creating ndarrays

In [11]:
data1 = [6, 7.5, 8, 0, 1]

In [12]:
arr1 = np.array(data1)

In [13]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [14]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [15]:
arr2 = np.array(data2)

In [16]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
arr2.ndim

2

In [18]:
arr2.shape

(2, 4)

# Bracket Indexing and Slicing

In [19]:
arr = np.arange(10)

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr[5]

5

In [21]:
arr[5:8]

array([5, 6, 7])

In [22]:
arr[5:8] = 12

In [24]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [25]:
arr_slice = arr[5:8]

In [26]:
arr_slice

array([12, 12, 12])

# arr

In [28]:
arr_slice[1] = 12345

In [33]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [29]:
arr_slice[:] = 64

In [30]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

# Arithmetic with Numpy Arrays

In [41]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [42]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [43]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [44]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [46]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [48]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [49]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [50]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

# 